env:
  global:
    secure: Douz/Y5L8iu2/ni2OxMRYtHvqlahxoxlnPCIHeyeSIPSGaqW1JKrRGVQQhieDyuA+jtH+p9V2kK5zM3Kg0j2VSXADYIMx4O4ziZZ5+eJ//70hQ9Y0wumeT6/Idbeotg+z3xDLauQxyEuoW72nu+jtdmOlkw7XBWhKckfxs2U/qE=
language: bash
script:
  - 'sh ./deploy_to_gh-pages.sh'