env:
  global:
    secure: UU6fpJzerciJ9nw5fvmsJpPSGWESQK0DRgA73RMIoIkPF0DUpwmGm4h8a42n5xMnl7jopMqVxf4OD4HKvobdzAUvgq5C09K3ASlhb+qBNN3ieRuOl9khaVBtDtaYI4SBvUTOPZuo7E7Bg/OxI7X1Hu/h5b6+NpoLHbwn2wl1VW0=
language: bash
script:
- sh ./deploy_to_gh-pages.sh
