env:
  global:
    secure: Douz/Y5L8iu2/ni2OxMRYtHvqlahxoxlnPCIHeyeSIPSGaqW1JKrRGVQQhieDyuA+jtH+p9V2kK5zM3Kg0j2VSXADYIMx4O4ziZZ5+eJ//70hQ9Y0wumeT6/Idbeotg+z3xDLauQxyEuoW72nu+jtdmOlkw7XBWhKckfxs2U/qE=
branches:
  except:
    - gh-pages
  only:
    - master
language: bash
before_install: 
  - 'git config --global user.email "riomus@gmail.com"'
  - 'git config --global user.name "Travis-CI"'
  - 'git config credential.helper "store --file=.git/credentials"'
  - 'echo "https://${GH_TOKEN}:@github.com" > .git/credentials'
script:
  - 'sh ./deploy_to_gh-pages.sh'