env:
  global:
    secure: Douz/Y5L8iu2/ni2OxMRYtHvqlahxoxlnPCIHeyeSIPSGaqW1JKrRGVQQhieDyuA+jtH+p9V2kK5zM3Kg0j2VSXADYIMx4O4ziZZ5+eJ//70hQ9Y0wumeT6/Idbeotg+z3xDLauQxyEuoW72nu+jtdmOlkw7XBWhKckfxs2U/qE=
branches:
  except:
    - RELEASE
  only:
    - master
language: node_js
node_js:
  - '0.12'
before_install: 
  - 'npm install -g grunt-cli'
  - 'npm install -g bower'
  - 'gem install sass'
  - 'git config --global user.email "riomus@gmail.com"'
  - 'git config --global user.name "Travis-CI"'
  - 'git config credential.helper "store --file=.git/credentials"'
  - 'echo "https://${GH_TOKEN}:@github.com" > .git/credentials'
install:
  - 'npm install'
  - 'bower install'
script:
  - 'grunt versioner'
  - 'grunt'
after_success:
  - 'grunt release'

