env:
 global:
  secure: UU6fpJzerciJ9nw5fvmsJpPSGWESQK0DRgA73RMIoIkPF0DUpwmGm4h8a42n5xMnl7jopMqVxf4OD4HKvobdzAUvgq5C09K3ASlhb+qBNN3ieRuOl9khaVBtDtaYI4SBvUTOPZuo7E7Bg/OxI7X1Hu/h5b6+NpoLHbwn2wl1VW0=
language: bash
script:
 - 'git config --global user.email "riomus@gmail.com"'
 - 'git config --global user.name "Travis-CI"'
 - 'git remote set-url origin https://${GH_TOKEN}@github.com/riomus/zosia-gesture-recognition.git'
 - sh ./deploy_to_gh-pages.sh
